"""empty message

Revision ID: 27224cb1795c
Revises: a83c7ae60bf9
Create Date: 2024-03-11 14:13:33.513579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27224cb1795c'
down_revision = 'a83c7ae60bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'description')
    # ### end Alembic commands ###
