"""empty message

Revision ID: 3277f96385ef
Revises: 27224cb1795c
Create Date: 2024-03-12 09:29:24.267675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3277f96385ef'
down_revision = '27224cb1795c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('expire_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'expire_time')
    # ### end Alembic commands ###
