"""empty message

Revision ID: 58858575313f
Revises: 3277f96385ef
Create Date: 2024-03-12 14:51:13.234570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58858575313f'
down_revision = '3277f96385ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('release_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice')
    # ### end Alembic commands ###
