"""empty message

Revision ID: a83c7ae60bf9
Revises: 6c5649fc84cd
Create Date: 2024-03-11 10:03:30.036321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83c7ae60bf9'
down_revision = '6c5649fc84cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('borrowers', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'borrowers')
    # ### end Alembic commands ###
